all:
		gcc -c main.c
		gcc -c insert_sort.c
		gcc -c select_sort.c
		gcc -c bubble_sort.c
		gcc -c quick_sort.c
		gcc main.o insert_sort.o select_sort.o bubble_sort.o quick_sort.o

clean:
		rm -f a.out *.o
